stages:
- unit_test
- security_scan
- build_and_push
- deploy_to_dev

variables:
 CHANGED_APP: ""
 DEV_BRANCH: "dev"

before_script:
- export CHANGED_APP=$(git diff --name-only $CI_COMMIT_BEFORE_SHA $CI_COMMIT_SHA | grep '^app-code/src/' | cut -d'/' -f3 | head -n1)

unit_test:
  stage: unit_test
  script:
    - echo "Running unit tests for $CHANGED_APP"
  only:
    refs:
      - merge_requests
    variables:
      - $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "dev"

security_scan:
  stage: security_scan
  script:
    - echo "Running SAST scan for $CHANGED_APP"
  only:
    refs:
      - merge_requests
    variables:
      - $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "dev"
 
build_and_push:
  stage: build_and_deploy
  script:
    - echo "Building docker image for $CHANGED_APP and pushing to ECR"
  only:
    refs:
      - merge_requests
    variables:
      - $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "dev"

deploy_to_dev:
  stage: deploy_to_dev
  script:
    - git config --global user.name "GitlabCI"
    - git checkout $DEV_BRANCH
    - git merge --no-ff $CI_COMMIT_REF_NAME
    - git push origin $DEV_BRANCH
  only:
    refs:
      - merge_requests
    variables:
      - $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "dev"