stages:
- unit_test
- security_scan
- build_and_push
- deploy_to_dev

variables:
  DEV_BRANCH: dev

unit_test:
  stage: unit_test
  script:
    - echo "Running unit tests for micro service"
  only:
    refs:
      - merge_requests
    variables:
      - $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "dev"

security_scan:
  stage: security_scan
  script:
    - echo "Running SAST scan for micro service"
  only:
    refs:
      - merge_requests
    variables:
      - $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "dev"

build_and_push:
  stage: build_and_push
  script:
    - echo "Building docker image for micro service and pushing to ECR"
  only:
    refs:
      - merge_requests
    variables:
      - $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "dev"

deploy_to_dev:
  stage: deploy_to_dev
  script:
    - git config --global user.name "GitlabCI"
    - git config --global user.email "gitlab@example.com"

    - git fetch origin $CI_COMMIT_REF_NAME
    - git checkout $CI_COMMIT_REF_NAME

    - git fetch origin $DEV_BRANCH
    - git checkout $DEV_BRANCH

    - git merge --no-ff $CI_COMMIT_REF_NAME
    - git push https://$GITLAB_USER:$ACCESS_TOKEN@gitlab.com/twn-devsecops-bootcamp/latest/online-boutique.git $DEV_BRANCH
  only:
    refs:
      - merge_requests
    variables:
      - $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "dev"