stages:
  - test
  - build
  - deploy

functional_tests:
  stage: test
  script:
    - echo "Running functional tests"

sast_scan:
  stage: test
  script:
    - echo "Running SAST scans"

sca_scan:
  stage: test
  script:
    - echo "Running SCA scans"

build_image:
  stage: build
  script:
    - echo "building the image"

image_scan:
  stage: build
  needs: ["build_image"]
  script:
    - echo "Running image scans"

push_image:
  stage: build
  needs: ["build_image", "image_scan"]
  script:
    - echo "Pushing image"

deploy:
  stage: deploy
  
  before_script:
    - export CI_COMMIT_SHORT_SHA=$(echo $CI_COMMIT_SHA | cut -c1-8)
    - export CHANGED_APP=$(git diff --name-only $CI_COMMIT_BEFORE_SHA $CI_COMMIT_SHA | grep '^apps/src/' | cut -d'/' -f3 | head -n1)
  script:
    - git config --global user.name "GitlabCI"
    - git checkout -b $PROD_BRANCH
    - git merge origin/dev
    - git push -v https://ajitraj:${AJIT_ACCESS_TOKEN}@gitlab.com/twn-devsecops-bootcamp/latest/onlineboutique.git $PROD_BRANCH
  only:
    - prod
  when: manual
