name: Trigger Target Workflow

on:
  workflow_dispatch:
    inputs:
      target_service:
        description: 'Input a service name (e.g., demo-app)'
        required: true
      target_version:
        description: 'Input a version (e.g., v1.0.0)'
        required: true

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Trigger Workflow in Another Repository
        run: |
          sh trigger_app_version_change.sh \
          ${{ secrets.PAT }} \
          ${{ github.event.inputs.target_service }} \
          ${{ github.event.inputs.target_version }}