name: Trigger ArgoCD Release
# Triggers the version change workflow in the target repository
# This is the workflow that will be triggered in the target repository:
# https://github.com/tonyrud/devsecops-online-boutique-k8s/blob/main/.github/workflows/trigger_deployment.yaml

on:
  workflow_dispatch:
    inputs:
      target_service:
        description: 'Input a service name (e.g., gcr-adservice)'
        required: true
      target_version:
        description: 'Input a version (e.g., v1.0.0)'
        required: true

env:
  PAT: ${{ secrets.PAT }}
  DISPATCH_REPO: devsecops-online-boutique-k8s
  DISPATCH_OWNER: tonyrud

jobs:
  trigger_argocd_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # manaully call workflow in another repository via REST API
      # - name: Trigger Workflow in Another Repository
      #   run: |
      #     sh trigger_app_version_change.sh \
      #     ${{ secrets.PAT }} \
      #     ${{ github.event.inputs.target_service }} \
      #     ${{ github.event.inputs.target_version }}

      - name: Dispatch an action and get the run ID
        uses: codex-/return-dispatch@v2
        id: return_dispatch
        with:
          ref: refs/heads/main
          workflow_timeout_seconds: 120
          workflow_job_steps_retry_seconds: 10
          token: ${{ secrets.PAT }}
          repo: ${{ env.DISPATCH_REPO }}
          owner: ${{ env.DISPATCH_OWNER }}
          workflow: trigger_deployment.yaml
          workflow_inputs: '{ "service": "${{ github.event.inputs.target_service }}", "version": "${{ github.event.inputs.target_version }}" }'
      
      - name: Await Run ID ${{ steps.return_dispatch.outputs.run_id }}
        uses: Codex-/await-remote-run@v1.0.0
        with:
          token: ${{ secrets.PAT }}
          repo: ${{ env.DISPATCH_REPO }}
          owner: ${{ env.DISPATCH_OWNER }}
          run_id: ${{ steps.return_dispatch.outputs.run_id }}